<?php
    $order = $this->getOrder();
?>

<!-- Facebook Conversion Code for Achats -->
<script type="text/javascript">
alert("facebook");
var fb_param = {};
fb_param.pixel_id = '<?php echo Mage::getStoreConfig('borriglione_facebookconversion/checkout_success/pixel_id'); ?>';
fb_param.value = '<?php echo round($order->getGrandTotal(), 2); ?>';
fb_param.currency = '<?php echo $order->getOrderCurrencyCode(); ?>';
(function()
{ var fpw = document.createElement('script'); fpw.async = true; fpw.src = '//connect.facebook.net/en_US/fp.js'; var ref = document.getElementsByTagName('script')[0]; ref.parentNode.insertBefore(fpw, ref); }

)();
</script>
<noscript>
    <img
        height="1"
        width="1"
        alt=""
        style="display:none"
        src="https://www.facebook.com/offsite_event.php?id=6015239811603&value=<?php echo round($order->getGrandTotal(), 2); ?>&currency=<?php echo $order->getOrderCurrencyCode(); ?>" />
</noscript>